source "https://rubygems.org"

gem "sinatra"

group :test do
  gem "rspec"
  gem "simplecov", require: false
  gem "cucumber"
  gem "capybara"
  gem "selenium-webdriver"
  gem 'sinatra-reloader', '~> 1.0'
end
